config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: [:index, :show, :new, :create]

  root to: 'posts#new'

end

app/models/post.rb
class Post < ActiveRecord::Base


  validates_presence_of :name, :age, :scale

def story_generate

  volume = scale.to_sym

# 事件
problems = {
        "10-20" => {
          s: [
            "去年の夏、近所で夏祭りが行われた",
            "先週、いつも通る道が工事によって通行止めになっていた",
            "今日、カレーを食べていた",
            "近頃、近隣住民はピンポンダッシュに悩まされていた",
          ],
          m: [
            "2014年、小保方教授がips細胞よりも簡単に作れるSTAP細胞を発表した",
            "2011年、52年ぶりに新燃岳が爆発的噴火を起こした",
            "2007年、後にノーベル賞を授与されることになった山中教授の手により万能細胞（iPS細胞）が作製された"
          ],
          l: [
            "2000年、ノストラダムスの予言が実現しようとしていた"
          ]
        },
        "20-30" => {
          s: [
            "去年の夏、近所で夏祭りが行われた",
            "先週、いつも通る道が工事によって通行止めになっていた",
            "今日、カレーを食べていた",
            "近頃、近隣住民はピンポンダッシュに悩まされていた",
          ],
          m: [
            "2014年、小保方教授がips細胞よりも簡単に作れるSTAP細胞を発表した",
            "2011年、52年ぶりに新燃岳が爆発的噴火を起こした",
            "2007年、後にノーベル賞を授与されることになった山中教授の手により万能細胞（iPS細胞）が作製された"
          ],
          l: [
            "2000年、ノストラダムスの予言が実現しようとしていた"
          ]
        },
        "30-50" => {
          s: [
            "去年の夏、近所で夏祭りが行われた",
            "先週、いつも通る道が工事によって通行止めになっていた",
            "今日、カレーを食べていた",
            "近頃、近隣住民はピンポンダッシュに悩まされていた",
          ],
          m: [
            "2014年、小保方教授がips細胞よりも簡単に作れるSTAP細胞を発表した",
            "2011年、52年ぶりに新燃岳が爆発的噴火を起こした",
            "2007年、後にノーベル賞を授与されることになった山中教授の手により万能細胞（iPS細胞）が作製された"
          ],
          l: [
            "10年前、世界はあの事件によって未曾有の危機にさらされた"
          ]
        },
        "other" => {
          s: [
            "去年の夏、近所で夏祭りが行われた",
            "先週、いつも通る道が工事によって通行止めになっていた",
            "今日、カレーを食べていた",
            "近頃、近隣住民はピンポンダッシュに悩まされていた",
          ],
          m: [
            "10年前、世界はあの事件によって未曾有の危機にさらされた",
            "10年前、世界はあの事件によって未曾有の危機にさらされた",
            "過去の悪夢が蘇ったその日、突如戦乱の渦に巻き込まれた平和な街があった",
            "2011年、52年ぶりに新燃岳が爆発的噴火を起こした",
            "2007年、後にノーベル賞を授与されることになった山中教授の手により万能細胞（iPS細胞）が作製された"
          ],
          l: [
            "人類の希望が、世界はあの事件によって未曾有の危機にさらされた"
          ]
        }
}

# 視界
views = [
        :裏で,
        :影に隠れて,
        :一方で,
        :歴史的事件を前に,
        :一見馬鹿な振る舞いで,
        :矢面に立って,
        :事態を静観しながら,
        :滅亡を回避するために,
        :歴史を塗り替えるために,
        :危機を感じつつも
        ]

# 行動
actions = [
        :糸を引いていた,
        :批判を逃れた,
        :批難を一身に受けた,
        :混乱に乗じた,
        :舞台を操っていた,
        :さらなる戦禍を巻き起こした,
        :遺憾の意を表明した,
        :謝罪会見を行った
        ]


# 結果
results = {
        s: [
          :勝利をもたらした,
          :近所で評判になった,
          :みんなに挨拶されるようになった,
          :宝くじにあたった,
          :地元で悪い奴は大体家来となった,
          :人気者になった,
          :親に叱られなくなった
        ],
        m: [
          :世界を救った,
          :全米を震撼させた,
          :経済危機を救った,
          :平和を実現した,
          :人類の発展に寄与した
        ],
        l: [
          :銀河を救った,
          :宇宙を震撼させた
        ]
}

# 肩書
titles = [
        :重要な,
        :大物,
        :死の,
        :音速の
]

# 役職
jobs = [
        :人物,
        :重鎮,
        :ニューヨーカー,
        :田舎者,
        :英雄的存在,
        :フィクサー,
        :タイムトラベラー,
        :CIA捜査官,
        :退役軍人,
        :魔法少女,
        :物理学者,
        :ヒップホッパー,
        :元刑事,
        :教授,
        :闇医者,
        :スパイ,
        :FBI捜査官,
        :シールズ,
        :特殊部隊グリーンベレー所属軍人,
        :密輸商人,
        :石油王の末裔,
        :スナイパー,
        :政治家,
        :暗殺者,
        :経済学者
]

self.story = "#{problems[age][volume].sample}。その#{views.sample}#{actions.sample}ことで#{results[volume].sample}#{titles.sample}#{jobs.sample}がいた事がアカシックレコードには記録されている。"

end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  DISPLAY_POSTS = 30

  def index
    @posts = Post.all.limit(DISPLAY_POSTS).order('id DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.story_generate
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  private
    def post_params
      params.require(:post).permit(:name, :age, :scale)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Akashic Record</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<%= yield %>

</html>

app/views/posts/_scale_m.html.erb
<div class="media">
	<div class="media-body">
		<h4 class="media-heading">
			世紀の発見の立役者。
		</h4>
		この発見ができたのは、彼の常に真摯な科学に向き合う姿勢と
		諦めない心に神様が
	</div>
	<a class="media-right" href="#">
		<img src="/img.svg" height="120" >
	</a>
</div>

app/views/posts/_scale_s.html.erb
<div class="media">
	<a class="media-left" href="#">
		<img src="/img.svg" height="120" >
	</a>
	<div class="media-body">
		<h4 class="media-heading">
			俺の部隊は彼によって救われた。
		</h4>
    ベトナムの地獄から生還できたのは <%= @post.name %> 、
		いつも冷静でポジティブな彼がいたからだ。
		彼のおかげで、俺たちは最高のチームだった。	
	</div>
</div>

app/views/posts/index.html.erb
<body>
<div class="container">
<div class="row">
	<div class="col-md-12">
  
    <h1>名を刻まれし者達</h1>
    <p>
    <%= link_to '汝名前を刻むに値する者か？', new_post_path %>
    </p>
    <% if @posts.present? %>
    <dl class="dl-horizontal">
    <% @posts.each do |post| %>
      <dt><%= post.name %></dt>
      <dd><%= post.story %></dd>
      <hr>
    <% end %>
    </dl>
    <% end %>
  </div>
</div>
</div>
</body>

app/views/posts/new.html.erb
<body style="background-image: url('http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/top_bg.png'); background-size: cover">

<div class="container"
     style="background-image: url('http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/top_titlebg.png');margin-top: 40px;">
	<div class="row">
		<img src="http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/top_title.png"
		     style="margin: auto; display: inherit; padding-top: 20px;">
 	</div>
	<div class="row" style="padding-top: 20px;">
		<div class="col-sm-2"></div>
		<div class="col-sm-8">
		  	<form class="form-horizontal" action="/posts" method="post">
		  		<div class="form-group">
		  			<label for="name" class="col-sm-2 control-label"
		  			       style="color: white;">
		  				Name
	  				</label>
	  				<div class="col-sm-10">
	  					<input type="text" class="form-control"
	  						   id="name" placeholder="Your name" name="post[name]">
	  				</div>
		  		</div>
		  		<div class="form-group">
		  			<label for="age" class="col-sm-2 control-label"
		  			       style="color: white;">
		  				Age
	  				</label>
	  				<div class="col-sm-10">
	  					<select class="form-control" name="post[age]">
	  						<option value="other"> Unknown </option>
	  						<option value="10-20"  > 10 - 20 </option>
	  						<option value="20-30"  > 20 - 30 </option>
	  						<option value="30-50"  > 30 - 50 </option>
	  					</select>
	  				</div>
		  		</div>
		  		<div class="form-group">
		  			<label for="age" class="col-sm-2 control-label"
		  			       style="color: white;">
		  				Scale
	  				</label>
	  				<div class="col-sm-10">
	  					<select class="form-control" name="post[scale]">
	  						<option value="s"> Local scale </option>
	  						<option value="m"> Country scale </option>
	  						<option value="l"> Cosmic scale </option>
	  					</select>
	  				</div>
		  		</div>
          <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
		  		<button 
		  		        style="padding: 0px; margin: auto; margin-top: 20px;
		  		         margin-left: 70px;">
		  		    <img src='http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/top_btn.png'>
		  		</button>
		  	</form>
		  	</div>
			<div class="col-sm-2"></div>
		</div>
	</div>
</div>
<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>

app/views/posts/show.html.erb
<body  style="background-image: url('http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/top_bg.png');">

<div class="container" style="background-image: url('http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/bg.png')">
	<div class="row" style="margin-top: 40px;">
		<div class="row namecard" style="height: 277px; margin-left:30px;">
			<div class="col-md-1"></div>
			<div class="col-md-10">
				<img src="http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/namecard_bg.png" style="width: 770px; height: 277px; ">
				<img src="http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/icon.jpeg" style="width: 150px; border-radius: 150px; position:relative; top: -190px; left: 100px;">
				<div style="position: relative; top: -370px; left: 350px; width: 300px; ">
          <div class="h1" id="username" style="font-weight: bold; text-align: center;"> <%= @post.name %> </div>
					<hr style="border-color: black">
					<div class="h2" id="userdesc" style="font-size:15px;text-align:center;">
            <%= @post.story %>
					</div>
				</div>
			</div>
			<div class="col-md-1"></div>
		</div>
		<div class="row"  style="position:relative;  top: -150px; left: 100px; width: 800px;">
			<div class="col-md-12">
				<img src="http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/line.png" width="800px" style="">
				<div class="media">
				  <a class="media-left" href="#">
				    <img src="http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/Einstein.jpg" height="200px;">
				  </a>
				  <div class="media-body">
				    <h2 class="media-heading">アインシュタイン</h2>
				    <h3>
				    	ニュートンがリンゴとであい万有引力を発見した。<br>
              私は <%= @post.name %> に出会い相対性理論を発見した。
				    </h3>
				  </div>
				</div>
			</div>
		</div>
		<div class="row"  style="position:relative;  top: -150px; left: 100px; width: 800px;">
			<div class="col-md-12">
				<img src="http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/line.png" width="800px" style="">
				<div class="media">
				  <div class="media-body">
				    <h2 class="media-heading">民間伝承</h2>
            <h3> 日本という国には、優秀な国民と豊かな自然、そして <%= @post.name %> がいる。 </h3>
				  </div>
				  <a class="media-right" href="#">
				    <img src="http://res.cloudinary.com/dehslhsf8/image/upload/v1421527588/king.jpg" height="200px;">
				  </a>

				</div>
			</div>
		</div>
		<div class="row"  style="position:relative;  top: -150px; left: 100px; width: 800px;">
			<div class="col-md-12">
				<img src="http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/line.png" width="800px" style="">
				<div class="media">
				  <a class="media-left" href="#">
				    <img src="http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/Michael_Jordan.jpg" height="200px;">
				  </a>
				  <div class="media-body">
				    <h2 class="media-heading">マイケルジョーダン</h4>
				    <h3> 俺は世界一になった。しかし、宇宙一にはなれなかった。 <br>
              (<%= @post.name %> を見ながらくやしそうに)
				    </h3>
				  </div>

				</div>
			</div>
		</div>
		<div class="row"  style="position:relative;  top: -150px; left: 100px; width: 800px;">
			<div class="col-md-12">
				<img src="http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/line.png" width="800px" style="">
				<div class="media">
				  <div class="media-body">
				    <h2 class="media-heading">E.T.</h2>
				    <h3>◯◆◯◯◯◯◆◯◯<br>
              (宇宙ができたのは　 <%= @post.name %>が 　我々と出会ったからだ)</h3>
				  </div>
				  <a class="media-right" href="#">
				    <img src="http://res.cloudinary.com/dehslhsf8/image/upload/v1421527533/uchujindesu.jpg" height="200px;">
				  </a>

				</div>
			</div>
		</div>
		<div class="row"  style="position:relative;  top: -100px; left: 100px;">
			<div class="col-md-12">
        <%= link_to '名を刻みし者達を見る', posts_path %>
			</div>
		</div>
	</div>

</div>
<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</body>